postgres:
    dialect: postgres
    datasource: dbname=test sslmode=disable
    dir: test-migrations

mysql:
    dialect: mysql
    datasource: root@/test?parseTime=true
    dir: test-migrations

mysql_noflag:
    dialect: mysql
    datasource: root@/test
    dir: test-migrations
